name: Release

on:
  push:
    branches:
      - master

jobs:
  dappnode-release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dappnodesdk and publishing package
      run: |
        sudo npm install @dappnode/dappnodesdk
        cp * /home/runner/work/DAppNodePackage-nethermind/DAppNodePackage-nethermind/node_modules/@dappnode/dappnodesdk/src
        cd node_modules/@dappnode/dappnodesdk/src
        node dappnodesdk.js publish patch -p infura --dappnode_team_preset GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
